### ISSUE TITLE
Consumed time /remaining time

### ISSUE THREAD

**Issue by chef88val** [schneefux/vscode-winddown#2]
This is a possitive comment:
Is it possible to see the remaining time or consumed time?

I'd like to ask you something, How many ways are there to reset time?
for example, Windows + L?

thank you so much for your time.

**Comment by schneefux** [comment]
Hi, at the moment, it is not possible to see any timers. I think that would create pressure. When you think about taking a break, just do it and relax for a moment - this extension is supposed to be a last resort when you are too deep into the zone.

Activity is detected within the VS Code window using cursor movements and some mouse events. 3 minutes of inactivity is considered a break, you can change this interval in the settings.
So if you lock your computer for 3 minutes, that counts as a break and the timer is reset.
