### ISSUE TITLE
Flickering issue

### ISSUE THREAD

**Issue by sadsa** [schneefux/vscode-winddown#3]
Loving this extension so far, so thanks for the great work! :)

I'm experiencing an issue whereby the screen will flicker as it begins to fade out the colours. Have you or any other users experienced this before?

**Comment by GWillmann** [comment]
Same here for the flicker!

And I love the extension also, thank you!

Config.: MacOs 10.15.3
Vscode: 1.44.1
Winddown.: 0.0.1

**Comment by schneefux** [comment]
When the colors change, VS Code flickers during the refresh.

I just published an update that skips some unnecessary refreshes.
In the settings, I added the parameter `winddown.framesPerMinute` - you can reduce it for fewer updates but that will make the transitions more noticable.

If you find good parameters, please share and I will make them default for everyone :)
