### ISSUE TITLE
Delay winddown by x minutes

### ISSUE THREAD

**Issue by GWillmann** [schneefux/vscode-winddown#4]
Sometimes when you are working on something and you are about to finish you don't want to stop before finishing.

What would you think about the possibility to delay the winddown by some minutes?

For example by adding either a shortcut or a button/link next to `you should take a break` ?

Thanks again

**Comment by schneefux** [comment]
This is a great idea! done in db3e8173acecfc18ecd185d90d32769f02c2730b & released as 0.0.3 🎉
