### ISSUE TITLE
Timer does not reset while laptop lid is closed (Ubuntu)

### ISSUE THREAD

**Issue by LuLaValva** [schneefux/vscode-winddown#7]
On Ubuntu 20.04

When activity is logged prior to closing laptop lid and it is closed for more than `minutesTillBreak`, Winddown starts fading as soon as the laptop is opened again.

I truly don't understand why this would be since updates are compared via timestamps, but I speculate that the way `setInterval` works while laptop lids are closed could be the root of the problem.

**Comment by schneefux** [comment]
Hi, sorry but I'm not actively working on this project. If you found a solution, feel free to open a PR.
